### ISSUE TITLE
Sidebar is always expanded

### ISSUE THREAD

**Issue by TheLalaMan** [NEOSidekick/NEOSidekick.AiAssistant#1]
It would be nice if the sidebar would not be expanded by default, especially when multiple people work with the Neos and on small screens. An option to configure this behaviour would also be appreciated!

**Comment by rolandschuetz** [comment]
Thanks for the feedback. I think that feature will come within the next two weeks.

**Comment by rolandschuetz** [comment]
@TheLalaMan The new version keeps the state after reloading and also has a fullscreen mode.
