### ISSUE TITLE
Copy function leads to console error

### ISSUE THREAD

**Issue by DrillSergeant** [NEOSidekick/NEOSidekick.AiAssistant#4]
When I use the copy-function (the icon next to the texts generated by the assistant), it does not end up in my clipboard. Instead there is a console error:
![image](https://github.com/NEOSidekick/NEOSidekick.AiAssistant/assets/883552/05cdb395-a205-4ba2-9b42-d49f8a080da2)

My browser: https://www.whatsmybrowser.org/b/QELC3

**Comment by rolandschuetz** [comment]
Thank you for the bug report, @DrillSergeant!

Unfortunately I can't reproduce this with either my Chromium (113) or Browserstack (Win 10, Chrome 113). 

To verify, you are on v1.4.1?

**Comment by DrillSergeant** [comment]
Yes, v1.4.1. And now I cannot reproduce it myself anymore. Strange....

Sorry for the noise, I will close this one and open again if I can reproduce it.

**Comment by rolandschuetz** [comment]
If you ever encounter the problem again, please let me know!
