### ISSUE TITLE
Use PHP 7.4 syntax

### ISSUE THREAD

**Issue by simonschaufi** [NEOSidekick/NEOSidekick.AiAssistant#5]
Since you also support older Neos Installations, not every installation runs on PHP 8.0 already like mine (Neos 7.3). This syntax is PHP 8 only: https://github.com/NEOSidekick/NEOSidekick.AiAssistant/blob/d2df498326781e0de64dd86c7aa85e42b7ab27d2/Classes/Controller/ServiceController.php#L70

Can you please backport that to PHP 7.4?

**Comment by rolandschuetz** [comment]
Thanks for the report. Fixed with https://github.com/NEOSidekick/NEOSidekick.AiAssistant/releases/tag/v1.4.2
